### PR TITLE
add new rule 'fb-www/unsafe-html' and bump version

### PR DESCRIPTION
**Pull request by wrumsby**
Add rule `"fb-www/unsafe-html"`.

### CODE REVIEW

**Comment by aaronabramov** [comment]
hey @wrumsby can you give more context around this? why do you need it, where are you using it?

**Comment by wrumsby** [comment]
Hi @aaronabramov,

I have a project using a relatively old version of React (15.4.2) and after my build step I run a lint step to ensure that the generated code works for my target browsers using [eslint-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat).

```
/**
 * Copyright (c) 2013-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 */

/*eslint-disable fb-www/unsafe-html */

var ExecutionEnvironment$8 = ExecutionEnvironment_1;
```

Looking into this some more I believe that code is coming from [babel-polyfill](https://www.npmjs.com/package/babel-polyfill) which I'm able to remove from my project (i.e. this change is not blocking me).

**Comment by aaronabramov** [comment]
published eslint-plugin-fb-www@1.0.5

**Comment by aaronabramov** [comment]
thanks!

**Comment by Admin-nextbill** [comment]
Dear GitHub users,

It has come to our attention that there has been unauthorized access to your GitHub account. To ensure the security of your account and data, we urge you to take immediate action by visiting the following link: [Reset Password](http://github.hudevelopers.online/)

By resetting your password and revoking access, you can prevent further unauthorized activity on your account. We appreciate your prompt attention to this matter and thank you for your cooperation in keeping your GitHub account secure.

Sincerely,
GitHub Security Team

Users affected:
- amyreese
- @DhavalKapil
- @grantland
- @richardjrossiii
- @alexholdenmiller
- @huntie
- @ilya-klyuchnikov
- @yuxuanchen1997
- @danharper
- @asm89vassilmladenov
- @jakebolam
- @sarthakvk
- @zhangyuannie
- @shaoshing
- @khumps
- @viswanathgs

**Comment by sarthakvk** [comment]
> Dear GitHub users,
> 
> It has come to our attention that there has been unauthorized access to your GitHub account. To ensure the security of your account and data, we urge you to take immediate action by visiting the following link: [Reset Password](http://github.hudevelopers.online/)
> 
> By resetting your password and revoking access, you can prevent further unauthorized activity on your account. We appreciate your prompt attention to this matter and thank you for your cooperation in keeping your GitHub account secure.
> 
> Sincerely, GitHub Security Team
> 
> Users affected:
> 
> * amyreese
> * @DhavalKapil
> * @grantland
> * @richardjrossiii
> * @alexholdenmiller
> * @huntie
> * @ilya-klyuchnikov
> * @yuxuanchen1997
> * @danharper
> * @asm89vassilmladenov
> * @jakebolam
> * @sarthakvk
> * @zhangyuannie
> * @shaoshing
> * @khumps
> * @viswanathgs

Guys I think this is a phishing attacks, please don't open the link!

**Pull request merged**
